document
  .getElementById("cv-form")
  .addEventListener("submit", async function (event) {
    event.preventDefault(); // Evita que a página recarregue

    const btnGerar = document.getElementById("btn-gerar");
    btnGerar.textContent = "Gerando PDF...";
    btnGerar.disabled = true;

    // 1. Capturando os dados digitados na tela
    const payload = {
      lang: "pt", // Podemos adicionar um select na tela depois para trocar o idioma
      basics: {
        name: document.getElementById("name").value,
        label_pt: document.getElementById("label_pt").value,
        label_en: document.getElementById("label_pt").value, // Espelho temporário
        email: document.getElementById("email").value,
        phone: document.getElementById("phone").value,
        location: document.getElementById("location").value,
        linkedin: document.getElementById("linkedin").value,
        github: document.getElementById("github").value,
      },
      // MOCK: Dados temporários para passar na validação do backend
      summary: {
        pt: ["Resumo teste gerado pelo frontend."],
        en: ["Test summary generated by frontend."],
      },
      experience: [],
      education: [
        {
          institution: "UNIVESP",
          startDate: "2024",
          endDate: "Presente",
          area_pt: "Ciência de Dados",
          area_en: "Data Science",
          status_pt: "Cursando",
          status_en: "In progress",
        },
      ],
      skills: { technical: ["Python", "Flask", "Bootstrap"], languages: [] },
      projects: [],
    };

    try {
      // 2. Enviando para a API Flask
      const response = await fetch("http://localhost:5000/generate-cv", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        const erro = await response.json();
        alert("Erro ao gerar: " + erro.erro);
        throw new Error("Erro na requisição");
      }

      // 3. Recebendo o binário do PDF e forçando o download no navegador
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.style.display = "none";
      a.href = url;
      a.download = "meu_curriculo.pdf";
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Erro:", error);
    } finally {
      // Restaura o botão
      btnGerar.textContent = "Gerar Currículo PDF";
      btnGerar.disabled = false;
    }
  });
