name: Gerar Curriculos PDF
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar Dependencias
        run: pip install jinja2 markupsafe

      - name: Rodar Gerador
        run: python gerador.py

      - name: ONDE ESTÃO OS ARQUIVOS? (DEBUG)
        run: |
          echo "Conteúdo da raiz:"
          ls -F
          echo "Conteúdo da pasta saida (se existir):"
          ls -F saida/ || echo "Pasta 'saida' não encontrada"

      - name: Mover arquivo para a raiz
        run: mv saida/curriculo_ats_pt.tex .

      - name: 📄 Compilar LaTeX para PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: curriculo_ats_pt.tex

      - name: Salvar PDF como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: curriculo-pdf
          path: curriculo_ats_pt.pdf # ou o caminho onde o PDF foi gerado
